language: node_js
node_js:
- '8'
- node
branches:
  only:
  - master
  # npm version tags
  - /^v\d+\.\d+\.\d+$/
cache:
  directories:
  - "$HOME/.npm"
env:
- TEST_COMMAND=test:fast
- TEST_COMMAND=test:slow
before_install:
- npm config set spin false
- if [ "$TRAVIS_NODE_VERSION" = "8" ]; then
    export NODE_LTS="true";
  fi
- which npx
# don't accidentally use the global npx
- rm $(which npx)
# sometimes this exists
# https://travis-ci.org/ember-cli/ember-cli-update/jobs/475792468#L96
- rm /usr/local/bin/npx || true
# test that we can't find it
- "! which npx"
script:
- npm run $TEST_COMMAND
jobs:
  allow_failures:
  - os: osx
  include:
  - env: TEST_COMMAND=lint
    before_install: ignore
  - os: osx
    env: TEST_COMMAND=test:slow
  - stage: Deploy
    cache: ignore
    env: ignore
    before_install: ignore
    install: ignore
    script: ignore
    deploy:
      provider: npm
      email: kellyselden@gmail.com
      api_key:
        secure: DbV7X+G3b/Wiz8ixkSZH2D3IJvSKLFtLchTdsrBTt3n5b0VFZYjecYxSFjr/JuEI80OJMIOvJCtMAx4IDl3cFo2dnbAiIqbpBup9zk9IOf/AJa7umvVwEIgvroIq73ODSa01W15wGgQ8lN5zU74qqyzjKNmDv4LPpQfSFWbF3w5lorQOkkhSA7liajK0Fbx1SONKYHJsv18RcDn36RJWyo0Woav336yxT/PixCVZS4V9ZdmbWaQgk17hnLi0OgS8vWYMnJDlyTGuj9lphS/Btni9K5KSvY55J58Df2K1NgIT6RJpQs+WW+hi5CMerpmEPHE+7kIZWp4DcrP8nJmNUH/9sNLpwGorafkQXgoJj+yX7SctCHqOwl60MhDI/cg1AvHh47iujJ9iq6mxxVvbV2dSK4VrNjbLKO04Hmg+h/n7NELfcjdlVL4KWoIEUv1I3O84p5TEq8cwBLtFJnHZSy9L3K8khOsX9P98H9MVW8B83mtxhET9BgbbmZDwObDXSDgfz/MGf3xhGw2pMDr4mhYwdw0k02vMnp1TYgyPp6DWrcaTyhg4moFxiRyBtaXJW3t26NsiFpWNw2z2X0hWGaYv6jSxY75/JfhpgX1tyi0GqOd16UMaUt9ID+Lsogx3qfsLbKYVXvdP/7+K2fAHU+44ZbQ9HPPNu8k0o/nzwoE=
      on:
        tags: true
        repo: ember-cli/ember-cli-update
